### ISSUE TITLE
Feature request: carry comments in the middle of function bodies down to LLBC

### ISSUE THREAD

**Issue by msprotz** [AeneasVerif/charon#340]
In the following snippet, I would like a way to retrieve the comment in LLBC.

```rust
fn foo() -> u32 {
 // Bar
  0
}
```

Possible thoughts include:
- looking up the text via span information
- using a rustdoc comment in the hope that it gets attached to an AST node
- ...?

Thanks!

**Comment by Nadrieril** [comment]
Turns out clippy has a lint that detects `// SAFETY` comments before unsafe blocks. They do span shenanigans to recover the comments. Code is [here](https://github.com/rust-lang/rust-clippy/blob/b86a202c92aec56daa3eee677bbc70493ac10394/clippy_lints/src/undocumented_unsafe_blocks.rs#L636) for inspiration.

**Comment by Nadrieril** [comment]
I made a decent attempt here: https://github.com/AeneasVerif/charon/pull/358, which is made mostly pointless by #233.

**Comment by Nadrieril** [comment]
Alright, this now works! The heuristic for where to place comments is quite naive however, so please report back if comments end up in surprising places.
