### ISSUE TITLE
Charon does not generate any output if there is an internal compiler error

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/charon#401]
Charon does not generate any output if there is an internal compiler error, even though it actually manages to recover from those errors.
Also, I note that if I copy [this code](https://github.com/AeneasVerif/charon/blob/8d66effc255d2fdc96d73fdc67b78271794bd681/charon/src/bin/charon-driver/main.rs#L212-L227) to move it [here](https://github.com/AeneasVerif/charon/blob/8d66effc255d2fdc96d73fdc67b78271794bd681/charon/src/bin/charon-driver/driver.rs#L282) then Charon outputs the serialized file. Maybe this is the solution?...

**Comment by sonmarcho** [comment]
> Does it output something with `--errors-as-warnings` in the case you're testing?

No that's the issue: in case there is a **rustc internal error** it doesn't output anything, even in the presence of`--errors-as-warnings` (which is actually expected, because `--errors-as-warnings` simply changes the way the Charon errors are reported - it doesn't have any effects on rustc's own errors).

**Comment by Nadrieril** [comment]
Hm I see. I presume what happens is that when we `catch_unwind` a compiler panic, this still eventually causes `run_compiler` to panic because the compiler remembers that it panicked.

In fact the export code used to be where you point to, I moved it because I wanted as little code as possible to be run within the compiler callbacks. Maybe I should just restore the `catch_unwind` around the compiler invocation

**Comment by sonmarcho** [comment]
Actually putting the code there where you put it perfectly makes sense to me: the only issue is that I don't think we can control those internal rustc errors (unless we manage to get rid of all of them of course ^^').
